### ISSUE TITLE
视频问题

### ISSUE THREAD

**Issue by Imbakae** [Dean1990/MagicCamera#6]
拍出来的视频有点渣啊，请问有没有什么解决方案

**Comment by Imbakae** [comment]
找到修改的位置了 Thanks
MagicCameraView.java 中设置

**Comment by lianyu-lc** [comment]
@Imbakae 录制视频的时候你会出现卡顿现象嘛？

**Comment by AndSync** [comment]
MagicCameraView中怎么设置啊？
